### ISSUE TITLE
Replace custom benchmarking with @Benchmark-ing

### ISSUE THREAD

**Issue by fuzzyweapon** [polyforest/acornui#121]
- [ ] Investigate `@Benchmark`ing solution
- [ ] Implement `@Benchmark`s
- [ ] Remove custom benchmark: `com.acornui.test.TestingUtilsKt#benchmark` in `acornui-utils/commonTest`

**Comment by fuzzyweapon** [comment]
Affects tests

**Comment by nbilyk** [comment]
There's now a common nanoElapsed() method
