### ISSUE TITLE
Refactor backend modules to be individual source sets for a single backend module.

### ISSUE THREAD

**Issue by fuzzyweapon** [polyforest/acornui#198]
## Currently
We model each backend as a whole MP module, so we end up with artifacts like:
- acornui-backend-lwjgl-jvm
- acornui-backend-lwjgl-js

Which doesn't make sense and is wasteful.

## Instead
We should model these as individual targets based on platform target presets...
```kotlin
kotlin {
    jvm("lwjgl")
    sourcesets {
        named("lwjglMain") {
            dependencies {
                // ...
            }
        }
    }
}
```

Which will give us tasks such as `compileKotlinLwjgl` instead of `compileKotlinJvm`.  This is provided by the Kotlin MPP plugin, but we'd have to programmatically create our run tasks as this is something our plugin provides (i.e. instead of just `runJvm` we'd have our plugin register `runLwjgl` or whatever task name pattern we wish such as `runJvmLwjgl`.  Whatever makes sense)

This means we can have each backend modeled as a different source set.  The use of source sets is even more valuable when wanting to share code between two source sets, but not **all** source sets (so it can't be in common).  It's worth looking into for other considerations.

What does this do to artifacts?
acornui-backend-lwjgl-js and acornui-backend-lwjgl-jvm won't ever be produced, and the artifact for lwjgl is now simply acornui-backend-lwjgl.

**Comment by nbilyk** [comment]
Backends no longer have unused targets set
