### ISSUE TITLE
Ctrl is not bound to CMD

### ISSUE THREAD

**Issue by fuzzyweapon** [polyforest/acornui#30]
MACs use CMD for ctrl for everything but terminal escape sequences (for obvious reasons).
We need to detect MACs when setting up keyboard input and map this instead.
Solution should not make the Ctrl key defunct.  It is common for MAC users to have or create application shortcuts with Ctrl (as it still exists on the keyboard).

**Comment by nbilyk** [comment]
There's a commandPlat property that binds to ctrl for windows and command for mac.
